// File generated by FlutterFire CLI & customized for Denk.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyFakeKeyForWebClientDenkSharedApp001',
    appId: '1:653774591983:web:denksharedexpensesappweb',
    messagingSenderId: '653774591983',
    projectId: 'denk-shared-expenses',
    authDomain: 'denk-shared-expenses.firebaseapp.com',
    storageBucket: 'denk-shared-expenses.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyFakeKeyForAndroidDenkSharedExpenses01',
    appId: '1:653774591983:android:com.denk.denk',
    messagingSenderId: '653774591983',
    projectId: 'denk-shared-expenses',
    storageBucket: 'denk-shared-expenses.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyFakeKeyForIosDenkSharedExpenses001',
    appId: '1:653774591983:ios:com.denk.denk',
    messagingSenderId: '653774591983',
    projectId: 'denk-shared-expenses',
    storageBucket: 'denk-shared-expenses.appspot.com',
    iosBundleId: 'com.denk.denk',
  );
}
